# Generated by Django 4.1.4 on 2022-12-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Football field', 'Football field'), ('Basketball field', 'Basketball field'), ('Volleyball field', 'Volleyball field'), ('Gym', 'Gym')], default='Doctor care', max_length=50),
        ),
    ]
