# Generated by Django 4.1.4 on 2022-12-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Football field', 'Football field'), ('Basketball field', 'Basketball field'), ('Volleyball field', 'Volleyball field'), ('Gym', 'Gym')], default='Football field', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('4 PM', '4 PM'), ('5 PM', '5 PM'), ('6 PM', '6 PM'), ('7 PM', '7 PM'), ('8 PM', '8 PM')], default='4 PM', max_length=10),
        ),
    ]
